#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Earlybound
{


    [System.Runtime.Serialization.DataContractAttribute()]
    public enum vhlb_column_type
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boolean = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decimal = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Integer = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lookup = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Memo = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Money = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Owner = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartyList = 10,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Picklist = 11,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        State = 12,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Status = 13,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 14,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uniqueidentifier = 15,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CalendarRules = 16,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Virtual = 17,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BigInt = 18,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManagedProperty = 19,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        EntityName = 20,
    }
}
#pragma warning restore CS1591
