#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum yp_gbl_column_definition_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_900AnyNavigateTo = 900,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_901AnyReadOnly = 901,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_902AnyRelatedRecords = 902,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_903AnyCopilotExecuteEvent = 903,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_904AnyDependentColors = 904,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_905AnyNewRelatedRecord = 905,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_906AnyNotes = 906,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_907AnyAuditHistory = 907,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_908AnyCustomTimeline = 908,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_909AnyColorbyHex = 909,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_800LookupNavigateTo = 800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_801LookupFilteredLookup = 801,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_700NumbersDateColors = 700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_701NumbersProgressBar = 701,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_702NumbersDuration = 702,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_600FileManagement = 600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_500TextRichTextPopover = 500,
	}
}
#pragma warning restore CS1591
