#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum yp_gbl_column_definition_shortcut
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CTRL = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SHIFT = 2,
	}
}
#pragma warning restore CS1591
