#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum yp_gbl_column_definition_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnyNavigateButtons = 900,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnyReadOnly = 901,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnyRelatedRecords = 902,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnyCopilotExecuteEvent = 903,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnyDependentColorfulCell = 904,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LookupNavigateButtons = 800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LookupFilteredLookup = 801,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NumbersDateColorfulCell = 700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NumbersProgressBar = 701,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FileUploadDownload = 600,
	}
}
#pragma warning restore CS1591
