#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// Select the navigation type of the app.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum appmodule_navigationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Singlesession = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Multisession = 1,
	}
	
	/// <summary>
	/// Status of the Model-driven App
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum appmodule_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Model-driven App
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum appmodule_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 3,
	}
	
	/// <summary>
	/// A role-based, modular business app that provides task-based functionality for a particular area of work.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("appmodule")]
	public partial class AppModule : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the appmodule entity
		/// </summary>
		public partial class Fields
		{
			public const string aiappdescription = "aiappdescription";
			public const string aidescriptiongeneratedon = "aidescriptiongeneratedon";
			public const string appgraph = "appgraph";
			public const string AppModuleId = "appmoduleid";
			public const string Id = "appmoduleid";
			public const string AppModuleIdUnique = "appmoduleidunique";
			public const string AppModuleVersion = "appmoduleversion";
			public const string AppModuleXmlManaged = "appmodulexmlmanaged";
			public const string ClientType = "clienttype";
			public const string ComponentState = "componentstate";
			public const string ConfigXML = "configxml";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string Description = "description";
			public const string Descriptor = "descriptor";
			public const string EventHandlers = "eventhandlers";
			public const string FormFactor = "formfactor";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IntroducedVersion = "introducedversion";
			public const string IsDefault = "isdefault";
			public const string IsFeatured = "isfeatured";
			public const string IsManaged = "ismanaged";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Name = "name";
			public const string NavigationType = "navigationtype";
			public const string OptimizedFor = "optimizedfor";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OverwriteTime = "overwritetime";
			public const string PublishedOn = "publishedon";
			public const string PublisherId = "publisherid";
			public const string SolutionId = "solutionid";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string UniqueName = "uniquename";
			public const string URL = "url";
			public const string VersionNumber = "versionnumber";
			public const string WebResourceId = "webresourceid";
			public const string WelcomePageId = "welcomepageid";
			public const string appmodule_appsetting_parentappmoduleid = "appmodule_appsetting_parentappmoduleid";
			public const string appmoduleroles_association = "appmoduleroles_association";
			public const string lk_appmodule_createdby = "lk_appmodule_createdby";
			public const string lk_appmodule_createdonbehalfby = "lk_appmodule_createdonbehalfby";
			public const string lk_appmodule_modifiedby = "lk_appmodule_modifiedby";
			public const string lk_appmodule_modifiedonbehalfby = "lk_appmodule_modifiedonbehalfby";
			public const string organization_appmodule = "organization_appmodule";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public AppModule() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "appmodule";
		
		public const string EntityLogicalCollectionName = "appmodules";
		
		public const string EntitySetName = "appmodules";
		
		/// <summary>
		/// This field is used to store AI generated Description for Model-driven App
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aiappdescription")]
		public string aiappdescription
		{
			get
			{
				return this.GetAttributeValue<string>("aiappdescription");
			}
			set
			{
				this.SetAttributeValue("aiappdescription", value);
			}
		}
		
		/// <summary>
		/// This field stores the Time when last AI App Description was generated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aidescriptiongeneratedon")]
		public System.Nullable<System.DateTime> aidescriptiongeneratedon
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aidescriptiongeneratedon");
			}
			set
			{
				this.SetAttributeValue("aidescriptiongeneratedon", value);
			}
		}
		
		/// <summary>
		/// This field is used to store App Graph for Model-driven App
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appgraph")]
		public string appgraph
		{
			get
			{
				return this.GetAttributeValue<string>("appgraph");
			}
			set
			{
				this.SetAttributeValue("appgraph", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmoduleid")]
		public System.Nullable<System.Guid> AppModuleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("appmoduleid");
			}
			set
			{
				this.SetAttributeValue("appmoduleid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmoduleid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.AppModuleId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the App Module used when synchronizing customizations for the Microsoft Dynamics 365 client for Outlook
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmoduleidunique")]
		public System.Nullable<System.Guid> AppModuleIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("appmoduleidunique");
			}
			set
			{
				this.SetAttributeValue("appmoduleidunique", value);
			}
		}
		
		/// <summary>
		/// App Module Version
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmoduleversion")]
		public string AppModuleVersion
		{
			get
			{
				return this.GetAttributeValue<string>("appmoduleversion");
			}
			set
			{
				this.SetAttributeValue("appmoduleversion", value);
			}
		}
		
		/// <summary>
		/// App Module Xml Managed
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appmodulexmlmanaged")]
		public string AppModuleXmlManaged
		{
			get
			{
				return this.GetAttributeValue<string>("appmodulexmlmanaged");
			}
			set
			{
				this.SetAttributeValue("appmodulexmlmanaged", value);
			}
		}
		
		/// <summary>
		/// Client Type such as Web or UCI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clienttype")]
		public System.Nullable<int> ClientType
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("clienttype");
			}
			set
			{
				this.SetAttributeValue("clienttype", value);
			}
		}
		
		/// <summary>
		/// For internal use only
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Contains configuration XML
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("configxml")]
		public string ConfigXML
		{
			get
			{
				return this.GetAttributeValue<string>("configxml");
			}
			set
			{
				this.SetAttributeValue("configxml", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Description for entity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// App Module Descriptor
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("descriptor")]
		public string Descriptor
		{
			get
			{
				return this.GetAttributeValue<string>("descriptor");
			}
		}
		
		/// <summary>
		/// App Module Event Handlers
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eventhandlers")]
		public string EventHandlers
		{
			get
			{
				return this.GetAttributeValue<string>("eventhandlers");
			}
			set
			{
				this.SetAttributeValue("eventhandlers", value);
			}
		}
		
		/// <summary>
		/// Form Factor
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("formfactor")]
		public System.Nullable<int> FormFactor
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("formfactor");
			}
			set
			{
				this.SetAttributeValue("formfactor", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the data import or data migration that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Version in which the similarity rule is introduced.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
		public string IntroducedVersion
		{
			get
			{
				return this.GetAttributeValue<string>("introducedversion");
			}
			set
			{
				this.SetAttributeValue("introducedversion", value);
			}
		}
		
		/// <summary>
		/// Is Default
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefault")]
		public System.Nullable<bool> IsDefault
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdefault");
			}
			set
			{
				this.SetAttributeValue("isdefault", value);
			}
		}
		
		/// <summary>
		/// Is Featured
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isfeatured")]
		public System.Nullable<bool> IsFeatured
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isfeatured");
			}
			set
			{
				this.SetAttributeValue("isfeatured", value);
			}
		}
		
		/// <summary>
		/// Is Managed
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Name of App Module
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// App navigation type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("navigationtype")]
		public virtual appmodule_navigationtype? NavigationType
		{
			get
			{
				return ((appmodule_navigationtype?)(EntityOptionSetEnum.GetEnum(this, "navigationtype")));
			}
			set
			{
				this.SetAttributeValue("navigationtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// The client that this app is optimized for
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("optimizedfor")]
		public string OptimizedFor
		{
			get
			{
				return this.GetAttributeValue<string>("optimizedfor");
			}
			set
			{
				this.SetAttributeValue("optimizedfor", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the organization associated with the app.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Internal use only
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Date and time when the record was published.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publishedon")]
		public System.Nullable<System.DateTime> PublishedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("publishedon");
			}
			set
			{
				this.SetAttributeValue("publishedon", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the publisher.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publisherid")]
		public Microsoft.Xrm.Sdk.EntityReference PublisherId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("publisherid");
			}
			set
			{
				this.SetAttributeValue("publisherid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Status of the Model-driven App
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual appmodule_statecode? statecode
		{
			get
			{
				return ((appmodule_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Model-driven App
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual appmodule_statuscode? statuscode
		{
			get
			{
				return ((appmodule_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique Name of App Module
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
		public string UniqueName
		{
			get
			{
				return this.GetAttributeValue<string>("uniquename");
			}
			set
			{
				this.SetAttributeValue("uniquename", value);
			}
		}
		
		/// <summary>
		/// Contains URL
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("url")]
		public string URL
		{
			get
			{
				return this.GetAttributeValue<string>("url");
			}
			set
			{
				this.SetAttributeValue("url", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the Web Resource
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("webresourceid")]
		public System.Nullable<System.Guid> WebResourceId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("webresourceid");
			}
			set
			{
				this.SetAttributeValue("webresourceid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the Web Resource as Welcome Page Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("welcomepageid")]
		public System.Nullable<System.Guid> WelcomePageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("welcomepageid");
			}
			set
			{
				this.SetAttributeValue("welcomepageid", value);
			}
		}
		
		/// <summary>
		/// 1:N appmodule_appsetting_parentappmoduleid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appmodule_appsetting_parentappmoduleid")]
		public System.Collections.Generic.IEnumerable<yopower_papps_grid_extensions.earlybound.AppSetting> appmodule_appsetting_parentappmoduleid
		{
			get
			{
				return this.GetRelatedEntities<yopower_papps_grid_extensions.earlybound.AppSetting>("appmodule_appsetting_parentappmoduleid", null);
			}
			set
			{
				this.SetRelatedEntities<yopower_papps_grid_extensions.earlybound.AppSetting>("appmodule_appsetting_parentappmoduleid", null, value);
			}
		}
		
		/// <summary>
		/// N:N appmoduleroles_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appmoduleroles_association")]
		public System.Collections.Generic.IEnumerable<yopower_papps_grid_extensions.earlybound.Role> appmoduleroles_association
		{
			get
			{
				return this.GetRelatedEntities<yopower_papps_grid_extensions.earlybound.Role>("appmoduleroles_association", null);
			}
			set
			{
				this.SetRelatedEntities<yopower_papps_grid_extensions.earlybound.Role>("appmoduleroles_association", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_appmodule_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_appmodule_createdby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_appmodule_createdby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_appmodule_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_appmodule_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_appmodule_createdonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_appmodule_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_appmodule_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_appmodule_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_appmodule_modifiedby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_appmodule_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_appmodule_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_appmodule_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_appmodule_modifiedonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_appmodule_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_appmodule_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 organization_appmodule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_appmodule")]
		public yopower_papps_grid_extensions.earlybound.Organization organization_appmodule
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.Organization>("organization_appmodule", null);
			}
		}
	}
}
#pragma warning restore CS1591
