#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// Developers can register plug-ins on a data provider to enable data access for virtual entities in the system.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("entitydataprovider")]
	public partial class EntityDataProvider : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the entitydataprovider entity
		/// </summary>
		public partial class Fields
		{
			public const string ArchivePlugin = "archiveplugin";
			public const string BulkArchivePlugin = "bulkarchiveplugin";
			public const string BulkRetainPlugin = "bulkretainplugin";
			public const string ComponentState = "componentstate";
			public const string CreateMultiplePlugin = "createmultipleplugin";
			public const string CreatePlugin = "createplugin";
			public const string DataSourceLogicalName = "datasourcelogicalname";
			public const string DeleteMultiplePlugin = "deletemultipleplugin";
			public const string DeletePlugin = "deleteplugin";
			public const string Description = "description";
			public const string EntityDataProviderId = "entitydataproviderid";
			public const string Id = "entitydataproviderid";
			public const string EntityDataProviderIdUnique = "entitydataprovideridunique";
			public const string IntroducedVersion = "introducedversion";
			public const string IsCustomizable = "iscustomizable";
			public const string IsManaged = "ismanaged";
			public const string LookupExpansionEnabled = "lookupexpansionenabled";
			public const string Name = "name";
			public const string OrganizationId = "organizationid";
			public const string OverwriteTime = "overwritetime";
			public const string PurgeArchivedContentPlugin = "purgearchivedcontentplugin";
			public const string PurgeRetainedContentPlugin = "purgeretainedcontentplugin";
			public const string RetainPlugin = "retainplugin";
			public const string RetrieveEntityChangesPlugin = "retrieveentitychangesplugin";
			public const string RetrieveMultiplePlugin = "retrievemultipleplugin";
			public const string RetrievePlugin = "retrieveplugin";
			public const string RollbackRetainPlugin = "rollbackretainplugin";
			public const string SolutionId = "solutionid";
			public const string UpdateMultiplePlugin = "updatemultipleplugin";
			public const string UpdatePlugin = "updateplugin";
			public const string UpsertMultiplePlugin = "upsertmultipleplugin";
			public const string UpsertPlugin = "upsertplugin";
			public const string ValidateArchiveConfigPlugin = "validatearchiveconfigplugin";
			public const string ValidateRetentionConfigPlugin = "validateretentionconfigplugin";
			public const string entitydataprovider_datasource = "entitydataprovider_datasource";
			public const string organization_entitydataprovider = "organization_entitydataprovider";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public EntityDataProvider() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "entitydataprovider";
		
		public const string EntityLogicalCollectionName = "entitydataproviders";
		
		public const string EntitySetName = "entitydataproviders";
		
		/// <summary>
		/// Contains the archiveplugin id that should be run when Archive is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("archiveplugin")]
		public System.Nullable<System.Guid> ArchivePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("archiveplugin");
			}
			set
			{
				this.SetAttributeValue("archiveplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the bulkarchiveplugin id that should be run when BulkArchive is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bulkarchiveplugin")]
		public System.Nullable<System.Guid> BulkArchivePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bulkarchiveplugin");
			}
			set
			{
				this.SetAttributeValue("bulkarchiveplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the bulkretainplugin id that should be run when BulkRetain is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bulkretainplugin")]
		public System.Nullable<System.Guid> BulkRetainPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bulkretainplugin");
			}
			set
			{
				this.SetAttributeValue("bulkretainplugin", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Contains the createmultipleplugin id that should be run when CreateMultiple is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createmultipleplugin")]
		public System.Nullable<System.Guid> CreateMultiplePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("createmultipleplugin");
			}
			set
			{
				this.SetAttributeValue("createmultipleplugin", value);
			}
		}
		
		/// <summary>
		/// Create Plugin
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createplugin")]
		public System.Nullable<System.Guid> CreatePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("createplugin");
			}
			set
			{
				this.SetAttributeValue("createplugin", value);
			}
		}
		
		/// <summary>
		/// When creating a Data Provider, the end user must select the name of the Data Source entity that will be created for the provider.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datasourcelogicalname")]
		public string DataSourceLogicalName
		{
			get
			{
				return this.GetAttributeValue<string>("datasourcelogicalname");
			}
			set
			{
				this.SetAttributeValue("datasourcelogicalname", value);
			}
		}
		
		/// <summary>
		/// Contains the deletemultipleplugin id that should be run when DeleteMultiple is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("deletemultipleplugin")]
		public System.Nullable<System.Guid> DeleteMultiplePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("deletemultipleplugin");
			}
			set
			{
				this.SetAttributeValue("deletemultipleplugin", value);
			}
		}
		
		/// <summary>
		/// Delete Plugin
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("deleteplugin")]
		public System.Nullable<System.Guid> DeletePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("deleteplugin");
			}
			set
			{
				this.SetAttributeValue("deleteplugin", value);
			}
		}
		
		/// <summary>
		/// What is this Data Provider used for and data store technologies does it target?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the data provider.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitydataproviderid")]
		public System.Nullable<System.Guid> EntityDataProviderId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entitydataproviderid");
			}
			set
			{
				this.SetAttributeValue("entitydataproviderid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitydataproviderid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.EntityDataProviderId = value;
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitydataprovideridunique")]
		public System.Nullable<System.Guid> EntityDataProviderIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entitydataprovideridunique");
			}
		}
		
		/// <summary>
		/// Version in which the form is introduced.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
		public string IntroducedVersion
		{
			get
			{
				return this.GetAttributeValue<string>("introducedversion");
			}
			set
			{
				this.SetAttributeValue("introducedversion", value);
			}
		}
		
		/// <summary>
		/// Information that specifies whether this component can be customized.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.SetAttributeValue("iscustomizable", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Enables expansion support for lookups columns. Only applicable to RetrieveMultiple plugin. Enabling this might modify the filter expression supplied to RetrieveMultiple plugin. Default value is false.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lookupexpansionenabled")]
		public System.Nullable<bool> LookupExpansionEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("lookupexpansionenabled");
			}
			set
			{
				this.SetAttributeValue("lookupexpansionenabled", value);
			}
		}
		
		/// <summary>
		/// The name of this Data Provider. This is the name that appears in the dropdown when creating a new entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public System.Nullable<System.Guid> OrganizationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("organizationid");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Contains the purgearchivedcontentplugin id that should be run when PurgeArchivedContent is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("purgearchivedcontentplugin")]
		public System.Nullable<System.Guid> PurgeArchivedContentPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("purgearchivedcontentplugin");
			}
			set
			{
				this.SetAttributeValue("purgearchivedcontentplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the purgeretainedcontentplugin id that should be run when PurgeRetainedContent is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("purgeretainedcontentplugin")]
		public System.Nullable<System.Guid> PurgeRetainedContentPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("purgeretainedcontentplugin");
			}
			set
			{
				this.SetAttributeValue("purgeretainedcontentplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the retainplugin id that should be run when Retain is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("retainplugin")]
		public System.Nullable<System.Guid> RetainPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("retainplugin");
			}
			set
			{
				this.SetAttributeValue("retainplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the retrieveentitychangesplugin id that should be run when RetrieveEntityChanges is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("retrieveentitychangesplugin")]
		public System.Nullable<System.Guid> RetrieveEntityChangesPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("retrieveentitychangesplugin");
			}
			set
			{
				this.SetAttributeValue("retrieveentitychangesplugin", value);
			}
		}
		
		/// <summary>
		/// MultipleRetrieve Plugin
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("retrievemultipleplugin")]
		public System.Nullable<System.Guid> RetrieveMultiplePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("retrievemultipleplugin");
			}
			set
			{
				this.SetAttributeValue("retrievemultipleplugin", value);
			}
		}
		
		/// <summary>
		/// Retrieve Plugin
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("retrieveplugin")]
		public System.Nullable<System.Guid> RetrievePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("retrieveplugin");
			}
			set
			{
				this.SetAttributeValue("retrieveplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the rollbackretainplugin id that should be run when Rollback Retain is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rollbackretainplugin")]
		public System.Nullable<System.Guid> RollbackRetainPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("rollbackretainplugin");
			}
			set
			{
				this.SetAttributeValue("rollbackretainplugin", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Contains the updatemultipleplugin id that should be run when UpdateMultiple is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("updatemultipleplugin")]
		public System.Nullable<System.Guid> UpdateMultiplePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("updatemultipleplugin");
			}
			set
			{
				this.SetAttributeValue("updatemultipleplugin", value);
			}
		}
		
		/// <summary>
		/// Update Plugin
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("updateplugin")]
		public System.Nullable<System.Guid> UpdatePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("updateplugin");
			}
			set
			{
				this.SetAttributeValue("updateplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the upsertmultipleplugin id that should be run when UpsertMultiple is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("upsertmultipleplugin")]
		public System.Nullable<System.Guid> UpsertMultiplePlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("upsertmultipleplugin");
			}
			set
			{
				this.SetAttributeValue("upsertmultipleplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the upsertplugin id that should be run when Upsert is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("upsertplugin")]
		public System.Nullable<System.Guid> UpsertPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("upsertplugin");
			}
			set
			{
				this.SetAttributeValue("upsertplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the validatearchiveconfigplugin id that should be run when ValidateArchiveConfig is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("validatearchiveconfigplugin")]
		public System.Nullable<System.Guid> ValidateArchiveConfigPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("validatearchiveconfigplugin");
			}
			set
			{
				this.SetAttributeValue("validatearchiveconfigplugin", value);
			}
		}
		
		/// <summary>
		/// Contains the validateretentionconfigplugin id that should be run when ValidateRetentionConfig is invoked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("validateretentionconfigplugin")]
		public System.Nullable<System.Guid> ValidateRetentionConfigPlugin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("validateretentionconfigplugin");
			}
			set
			{
				this.SetAttributeValue("validateretentionconfigplugin", value);
			}
		}
		
		/// <summary>
		/// 1:N entitydataprovider_datasource
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitydataprovider_datasource")]
		public System.Collections.Generic.IEnumerable<yopower_papps_grid_extensions.earlybound.EntityDataSource> entitydataprovider_datasource
		{
			get
			{
				return this.GetRelatedEntities<yopower_papps_grid_extensions.earlybound.EntityDataSource>("entitydataprovider_datasource", null);
			}
			set
			{
				this.SetRelatedEntities<yopower_papps_grid_extensions.earlybound.EntityDataSource>("entitydataprovider_datasource", null, value);
			}
		}
		
		/// <summary>
		/// N:1 organization_entitydataprovider
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_entitydataprovider")]
		public yopower_papps_grid_extensions.earlybound.Organization organization_entitydataprovider
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.Organization>("organization_entitydataprovider", null);
			}
		}
	}
}
#pragma warning restore CS1591
