#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// Internal entity that stores data source information for all installed providers.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("entitydatasource")]
	public partial class EntityDataSource : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the entitydatasource entity
		/// </summary>
		public partial class Fields
		{
			public const string ComponentState = "componentstate";
			public const string ConnectionDefinition = "connectiondefinition";
			public const string ConnectionDefinitionSecrets = "connectiondefinitionsecrets";
			public const string Description = "description";
			public const string EntityDataProviderId = "entitydataproviderid";
			public const string EntityDataSourceId = "entitydatasourceid";
			public const string Id = "entitydatasourceid";
			public const string EntityDataSourceIdUnique = "entitydatasourceidunique";
			public const string EntityName = "entityname";
			public const string IntroducedVersion = "introducedversion";
			public const string IsCustomizable = "iscustomizable";
			public const string IsManaged = "ismanaged";
			public const string Name = "name";
			public const string OrganizationId = "organizationid";
			public const string OverwriteTime = "overwritetime";
			public const string SolutionId = "solutionid";
			public const string entitydataprovider_datasource = "entitydataprovider_datasource";
			public const string organization_entitydatasource = "organization_entitydatasource";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public EntityDataSource() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "entitydatasource";
		
		public const string EntityLogicalCollectionName = "entitydatasources";
		
		public const string EntitySetName = "entitydatasources";
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// JSON data representing values from a data source entity as individual fields.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectiondefinition")]
		public string ConnectionDefinition
		{
			get
			{
				return this.GetAttributeValue<string>("connectiondefinition");
			}
			set
			{
				this.SetAttributeValue("connectiondefinition", value);
			}
		}
		
		/// <summary>
		/// JSON data representing secrets in a data source entity as individual fields.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectiondefinitionsecrets")]
		public string ConnectionDefinitionSecrets
		{
			get
			{
				return this.GetAttributeValue<string>("connectiondefinitionsecrets");
			}
			set
			{
				this.SetAttributeValue("connectiondefinitionsecrets", value);
			}
		}
		
		/// <summary>
		/// Enter additional information to describe the environment this data source targets and the purpose of this system.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Choose the entity dataprovider for the entity datasource.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitydataproviderid")]
		public Microsoft.Xrm.Sdk.EntityReference EntityDataProviderId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("entitydataproviderid");
			}
			set
			{
				this.SetAttributeValue("entitydataproviderid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the Data Source Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitydatasourceid")]
		public System.Nullable<System.Guid> EntityDataSourceId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entitydatasourceid");
			}
			set
			{
				this.SetAttributeValue("entitydatasourceid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitydatasourceid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.EntityDataSourceId = value;
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitydatasourceidunique")]
		public System.Nullable<System.Guid> EntityDataSourceIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entitydatasourceidunique");
			}
		}
		
		/// <summary>
		/// Entity Logical Name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityname")]
		public string EntityName
		{
			get
			{
				return this.GetAttributeValue<string>("entityname");
			}
			set
			{
				this.SetAttributeValue("entityname", value);
			}
		}
		
		/// <summary>
		/// Version in which the form is introduced.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
		public string IntroducedVersion
		{
			get
			{
				return this.GetAttributeValue<string>("introducedversion");
			}
			set
			{
				this.SetAttributeValue("introducedversion", value);
			}
		}
		
		/// <summary>
		/// Information that specifies whether this component can be customized.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.SetAttributeValue("iscustomizable", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Name of this data source. This name appears in the data source drop-down when creating a new entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public System.Nullable<System.Guid> OrganizationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("organizationid");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// N:1 entitydataprovider_datasource
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitydataproviderid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitydataprovider_datasource")]
		public yopower_papps_grid_extensions.earlybound.EntityDataProvider entitydataprovider_datasource
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.EntityDataProvider>("entitydataprovider_datasource", null);
			}
			set
			{
				this.SetRelatedEntity<yopower_papps_grid_extensions.earlybound.EntityDataProvider>("entitydataprovider_datasource", null, value);
			}
		}
		
		/// <summary>
		/// N:1 organization_entitydatasource
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_entitydatasource")]
		public yopower_papps_grid_extensions.earlybound.Organization organization_entitydatasource
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.Organization>("organization_entitydatasource", null);
			}
		}
	}
}
#pragma warning restore CS1591
