#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// State of the Language Code
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum languagelocale_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the LanguageCode.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum languagelocale_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Language
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("languagelocale")]
	public partial class LanguageLocale : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the languagelocale entity
		/// </summary>
		public partial class Fields
		{
			public const string Code = "code";
			public const string Language = "language";
			public const string LanguageLocaleId = "languagelocaleid";
			public const string Id = "languagelocaleid";
			public const string LocaleId = "localeid";
			public const string Name = "name";
			public const string OrganizationId = "organizationid";
			public const string Region = "region";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string VersionNumber = "versionnumber";
			public const string languagelocale_organization = "languagelocale_organization";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public LanguageLocale() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "languagelocale";
		
		public const string EntityLogicalCollectionName = "languagelocales";
		
		public const string EntitySetName = "languagelocale";
		
		/// <summary>
		/// Code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("code")]
		public string Code
		{
			get
			{
				return this.GetAttributeValue<string>("code");
			}
		}
		
		/// <summary>
		/// Language
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("language")]
		public string Language
		{
			get
			{
				return this.GetAttributeValue<string>("language");
			}
		}
		
		/// <summary>
		/// LanguageLocaleId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("languagelocaleid")]
		public System.Nullable<System.Guid> LanguageLocaleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("languagelocaleid");
			}
			set
			{
				this.SetAttributeValue("languagelocaleid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("languagelocaleid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.LanguageLocaleId = value;
			}
		}
		
		/// <summary>
		/// Locale ID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("localeid")]
		public System.Nullable<int> LocaleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("localeid");
			}
			set
			{
				this.SetAttributeValue("localeid", value);
			}
		}
		
		/// <summary>
		/// Name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
		}
		
		/// <summary>
		/// Unique identifier of the organization associated with the language locale.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Region
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("region")]
		public string Region
		{
			get
			{
				return this.GetAttributeValue<string>("region");
			}
		}
		
		/// <summary>
		/// State Code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual languagelocale_statecode? statecode
		{
			get
			{
				return ((languagelocale_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Language Status Code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual languagelocale_statuscode? statuscode
		{
			get
			{
				return ((languagelocale_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 languagelocale_organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("languagelocale_organization")]
		public yopower_papps_grid_extensions.earlybound.Organization languagelocale_organization
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.Organization>("languagelocale_organization", null);
			}
		}
	}
}
#pragma warning restore CS1591
