#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// Status of the view.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum savedquery_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the view.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum savedquery_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Saved query against the database.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("savedquery")]
	public partial class SavedQuery : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the savedquery entity
		/// </summary>
		public partial class Fields
		{
			public const string AdvancedGroupBy = "advancedgroupby";
			public const string CanBeDeleted = "canbedeleted";
			public const string ColumnSetXml = "columnsetxml";
			public const string ComponentState = "componentstate";
			public const string ConditionalFormatting = "conditionalformatting";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string Description = "description";
			public const string EnableCrossPartition = "enablecrosspartition";
			public const string FetchXml = "fetchxml";
			public const string IntroducedVersion = "introducedversion";
			public const string IsCustom = "iscustom";
			public const string IsCustomizable = "iscustomizable";
			public const string IsDefault = "isdefault";
			public const string IsManaged = "ismanaged";
			public const string IsPrivate = "isprivate";
			public const string IsQuickFindQuery = "isquickfindquery";
			public const string IsUserDefined = "isuserdefined";
			public const string LayoutJson = "layoutjson";
			public const string LayoutXml = "layoutxml";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Name = "name";
			public const string OfflineSqlQuery = "offlinesqlquery";
			public const string OrganizationId = "organizationid";
			public const string OrganizationTabOrder = "organizationtaborder";
			public const string OverwriteTime = "overwritetime";
			public const string QueryAPI = "queryapi";
			public const string QueryAppUsage = "queryappusage";
			public const string QueryType = "querytype";
			public const string ReturnedTypeCode = "returnedtypecode";
			public const string RoleDisplayConditionsXml = "roledisplayconditionsxml";
			public const string SavedQueryId = "savedqueryid";
			public const string Id = "savedqueryid";
			public const string SavedQueryIdUnique = "savedqueryidunique";
			public const string SolutionId = "solutionid";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string VersionNumber = "versionnumber";
			public const string lk_savedquery_createdonbehalfby = "lk_savedquery_createdonbehalfby";
			public const string lk_savedquery_modifiedonbehalfby = "lk_savedquery_modifiedonbehalfby";
			public const string lk_savedquerybase_createdby = "lk_savedquerybase_createdby";
			public const string lk_savedquerybase_modifiedby = "lk_savedquerybase_modifiedby";
			public const string organization_saved_queries = "organization_saved_queries";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public SavedQuery() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "savedquery";
		
		public const string EntityLogicalCollectionName = "savedqueries";
		
		public const string EntitySetName = "savedqueries";
		
		/// <summary>
		/// Type the column name that will be used to group the results from the data collected across multiple records from a system view.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("advancedgroupby")]
		public string AdvancedGroupBy
		{
			get
			{
				return this.GetAttributeValue<string>("advancedgroupby");
			}
			set
			{
				this.SetAttributeValue("advancedgroupby", value);
			}
		}
		
		/// <summary>
		/// Tells whether the view can be deleted.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbedeleted")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty CanBeDeleted
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("canbedeleted");
			}
			set
			{
				this.SetAttributeValue("canbedeleted", value);
			}
		}
		
		/// <summary>
		/// Contains the columns and sorting criteria for the view, stored in XML format.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("columnsetxml")]
		public string ColumnSetXml
		{
			get
			{
				return this.GetAttributeValue<string>("columnsetxml");
			}
			set
			{
				this.SetAttributeValue("columnsetxml", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Type information about how the items in the system view are formatted.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("conditionalformatting")]
		public string ConditionalFormatting
		{
			get
			{
				return this.GetAttributeValue<string>("conditionalformatting");
			}
			set
			{
				this.SetAttributeValue("conditionalformatting", value);
			}
		}
		
		/// <summary>
		/// Shows who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Type additional information to describe the view, such as the filter criteria or intended results set.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Tells whether the view can retrieve data from all cluster partitions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("enablecrosspartition")]
		public System.Nullable<bool> EnableCrossPartition
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("enablecrosspartition");
			}
			set
			{
				this.SetAttributeValue("enablecrosspartition", value);
			}
		}
		
		/// <summary>
		/// String specifying the query in Fetch XML language.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fetchxml")]
		public string FetchXml
		{
			get
			{
				return this.GetAttributeValue<string>("fetchxml");
			}
			set
			{
				this.SetAttributeValue("fetchxml", value);
			}
		}
		
		/// <summary>
		/// Version in which the form is introduced.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
		public string IntroducedVersion
		{
			get
			{
				return this.GetAttributeValue<string>("introducedversion");
			}
			set
			{
				this.SetAttributeValue("introducedversion", value);
			}
		}
		
		/// <summary>
		/// Tells whether a user created the view.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustom")]
		public System.Nullable<bool> IsCustom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("iscustom");
			}
		}
		
		/// <summary>
		/// Tells whether the component can be customized.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.SetAttributeValue("iscustomizable", value);
			}
		}
		
		/// <summary>
		/// Tells whether the view is the default view for the specified record type (entity).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefault")]
		public System.Nullable<bool> IsDefault
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdefault");
			}
			set
			{
				this.SetAttributeValue("isdefault", value);
			}
		}
		
		/// <summary>
		/// Tells whether the record is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Indicates whether or not this is viewable by the entire organization.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isprivate")]
		[System.ObsoleteAttribute()]
		public System.Nullable<bool> IsPrivate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isprivate");
			}
		}
		
		/// <summary>
		/// Choose whether the view is compatible with Quick Find. When users search for specific items, you define the fields that are searched in.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isquickfindquery")]
		public System.Nullable<bool> IsQuickFindQuery
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isquickfindquery");
			}
			set
			{
				this.SetAttributeValue("isquickfindquery", value);
			}
		}
		
		/// <summary>
		/// Tells whether the view was created by a user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isuserdefined")]
		public System.Nullable<bool> IsUserDefined
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isuserdefined");
			}
		}
		
		/// <summary>
		/// Layout data in JSON format.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("layoutjson")]
		public string LayoutJson
		{
			get
			{
				return this.GetAttributeValue<string>("layoutjson");
			}
			set
			{
				this.SetAttributeValue("layoutjson", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("layoutxml")]
		public string LayoutXml
		{
			get
			{
				return this.GetAttributeValue<string>("layoutxml");
			}
			set
			{
				this.SetAttributeValue("layoutxml", value);
			}
		}
		
		/// <summary>
		/// Shows who last updated the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Type a name for the view to describe what results the view will contain. This name is visible to users in the View list.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// String specifying the corresponding sql query for the fetch xml specified for offline use.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("offlinesqlquery")]
		public string OfflineSqlQuery
		{
			get
			{
				return this.GetAttributeValue<string>("offlinesqlquery");
			}
			set
			{
				this.SetAttributeValue("offlinesqlquery", value);
			}
		}
		
		/// <summary>
		/// Choose the ID of the organization that the record is associated with.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// For the organization, type the tab order to determine how users navigate through the screen using only the Tab key.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationtaborder")]
		public System.Nullable<int> OrganizationTabOrder
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("organizationtaborder");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queryapi")]
		public string QueryAPI
		{
			get
			{
				return this.GetAttributeValue<string>("queryapi");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queryappusage")]
		public System.Nullable<int> QueryAppUsage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("queryappusage");
			}
			set
			{
				this.SetAttributeValue("queryappusage", value);
			}
		}
		
		/// <summary>
		/// Shows the type of the query.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("querytype")]
		public System.Nullable<int> QueryType
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("querytype");
			}
			set
			{
				this.SetAttributeValue("querytype", value);
			}
		}
		
		/// <summary>
		/// Type of entity displayed in the view.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("returnedtypecode")]
		public string ReturnedTypeCode
		{
			get
			{
				return this.GetAttributeValue<string>("returnedtypecode");
			}
			set
			{
				this.SetAttributeValue("returnedtypecode", value);
			}
		}
		
		/// <summary>
		/// Contains the role display conditions for the SavedQuery.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("roledisplayconditionsxml")]
		public string RoleDisplayConditionsXml
		{
			get
			{
				return this.GetAttributeValue<string>("roledisplayconditionsxml");
			}
			set
			{
				this.SetAttributeValue("roledisplayconditionsxml", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the view.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("savedqueryid")]
		public System.Nullable<System.Guid> SavedQueryId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("savedqueryid");
			}
			set
			{
				this.SetAttributeValue("savedqueryid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("savedqueryid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SavedQueryId = value;
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("savedqueryidunique")]
		public System.Nullable<System.Guid> SavedQueryIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("savedqueryidunique");
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Shows the status of the view.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual savedquery_statecode? StateCode
		{
			get
			{
				return ((savedquery_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Shows the reason code that explains the status of the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual savedquery_statuscode? StatusCode
		{
			get
			{
				return ((savedquery_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Version number of the view.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 lk_savedquery_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_savedquery_createdonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_savedquery_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_savedquery_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_savedquery_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_savedquery_modifiedonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_savedquery_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_savedquery_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_savedquerybase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_savedquerybase_createdby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_savedquerybase_createdby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_savedquerybase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_savedquerybase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_savedquerybase_modifiedby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_savedquerybase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_savedquerybase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 organization_saved_queries
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_saved_queries")]
		public yopower_papps_grid_extensions.earlybound.Organization organization_saved_queries
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.Organization>("organization_saved_queries", null);
			}
		}
	}
}
#pragma warning restore CS1591
