#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// Data type of Setting Definition.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum settingdefinition_datatype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 2,
	}
	
	/// <summary>
	/// Overridable level of Setting Definition.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum settingdefinition_overridablelevel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppAndOrganization = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationOnly = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppOnly = 2,
	}
	
	/// <summary>
	/// Release level of Setting Definition.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum settingdefinition_releaselevel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GA = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EarlyAccess = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preview = 2,
	}
	
	/// <summary>
	/// Status of the SettingDefinition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum settingdefinition_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the SettingDefinition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum settingdefinition_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Contains Setting Definitions
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("settingdefinition")]
	public partial class SettingDefinition : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the settingdefinition entity
		/// </summary>
		public partial class Fields
		{
			public const string ComponentIdUnique = "componentidunique";
			public const string ComponentState = "componentstate";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string DataType = "datatype";
			public const string DefaultValue = "defaultvalue";
			public const string Description = "description";
			public const string DisplayName = "displayname";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string InformationUrl = "informationurl";
			public const string IsCustomizable = "iscustomizable";
			public const string IsHidden = "ishidden";
			public const string IsManaged = "ismanaged";
			public const string IsOverridable = "isoverridable";
			public const string IsPlatform = "isplatform";
			public const string IsPreview = "ispreview";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string OverridableLevel = "overridablelevel";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OverwriteTime = "overwritetime";
			public const string ReleaseLevel = "releaselevel";
			public const string SettingDefinitionId = "settingdefinitionid";
			public const string Id = "settingdefinitionid";
			public const string SolutionId = "solutionid";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UniqueName = "uniquename";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string settingdefinition_appsetting_settingdefinitionid = "settingdefinition_appsetting_settingdefinitionid";
			public const string settingdefinition_organizationsetting_settingdefinitionid = "settingdefinition_organizationsetting_settingdefinitionid";
			public const string lk_settingdefinition_createdby = "lk_settingdefinition_createdby";
			public const string lk_settingdefinition_createdonbehalfby = "lk_settingdefinition_createdonbehalfby";
			public const string lk_settingdefinition_modifiedby = "lk_settingdefinition_modifiedby";
			public const string lk_settingdefinition_modifiedonbehalfby = "lk_settingdefinition_modifiedonbehalfby";
			public const string organization_settingdefinition = "organization_settingdefinition";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public SettingDefinition() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "settingdefinition";
		
		public const string EntityLogicalCollectionName = "settingdefinitions";
		
		public const string EntitySetName = "settingdefinitions";
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
		public System.Nullable<System.Guid> ComponentIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Data type of Setting Definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datatype")]
		public virtual settingdefinition_datatype? DataType
		{
			get
			{
				return ((settingdefinition_datatype?)(EntityOptionSetEnum.GetEnum(this, "datatype")));
			}
			set
			{
				this.SetAttributeValue("datatype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Default value to be used, if there is no associated App Setting Value.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultvalue")]
		public string DefaultValue
		{
			get
			{
				return this.GetAttributeValue<string>("defaultvalue");
			}
			set
			{
				this.SetAttributeValue("defaultvalue", value);
			}
		}
		
		/// <summary>
		/// The description of the Setting Definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Display name of the Setting Definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("displayname")]
		public string DisplayName
		{
			get
			{
				return this.GetAttributeValue<string>("displayname");
			}
			set
			{
				this.SetAttributeValue("displayname", value);
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Specifies information url of the setting.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("informationurl")]
		public string InformationUrl
		{
			get
			{
				return this.GetAttributeValue<string>("informationurl");
			}
			set
			{
				this.SetAttributeValue("informationurl", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.SetAttributeValue("iscustomizable", value);
			}
		}
		
		/// <summary>
		/// Specifies whether settings is hidden from ui designer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ishidden")]
		public System.Nullable<bool> IsHidden
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ishidden");
			}
			set
			{
				this.SetAttributeValue("ishidden", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Specifies whether settings can be overridden at an app or org level by other publishers.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isoverridable")]
		public System.Nullable<bool> IsOverridable
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isoverridable");
			}
			set
			{
				this.SetAttributeValue("isoverridable", value);
			}
		}
		
		/// <summary>
		/// Specifies whether setting is a internal platform setting.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isplatform")]
		public System.Nullable<bool> IsPlatform
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isplatform");
			}
			set
			{
				this.SetAttributeValue("isplatform", value);
			}
		}
		
		/// <summary>
		/// Specifies whether settings controls the flighting a preview feature.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ispreview")]
		public System.Nullable<bool> IsPreview
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ispreview");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Overridable Level of Setting Definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overridablelevel")]
		public virtual settingdefinition_overridablelevel? OverridableLevel
		{
			get
			{
				return ((settingdefinition_overridablelevel?)(EntityOptionSetEnum.GetEnum(this, "overridablelevel")));
			}
			set
			{
				this.SetAttributeValue("overridablelevel", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Specifies settings release level.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("releaselevel")]
		public virtual settingdefinition_releaselevel? ReleaseLevel
		{
			get
			{
				return ((settingdefinition_releaselevel?)(EntityOptionSetEnum.GetEnum(this, "releaselevel")));
			}
			set
			{
				this.SetAttributeValue("releaselevel", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("settingdefinitionid")]
		public System.Nullable<System.Guid> SettingDefinitionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("settingdefinitionid");
			}
			set
			{
				this.SetAttributeValue("settingdefinitionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("settingdefinitionid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SettingDefinitionId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Status of the SettingDefinition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual settingdefinition_statecode? statecode
		{
			get
			{
				return ((settingdefinition_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the SettingDefinition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual settingdefinition_statuscode? statuscode
		{
			get
			{
				return ((settingdefinition_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique name of the Setting Definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
		public string UniqueName
		{
			get
			{
				return this.GetAttributeValue<string>("uniquename");
			}
			set
			{
				this.SetAttributeValue("uniquename", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N settingdefinition_appsetting_settingdefinitionid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("settingdefinition_appsetting_settingdefinitionid")]
		public System.Collections.Generic.IEnumerable<yopower_papps_grid_extensions.earlybound.AppSetting> settingdefinition_appsetting_settingdefinitionid
		{
			get
			{
				return this.GetRelatedEntities<yopower_papps_grid_extensions.earlybound.AppSetting>("settingdefinition_appsetting_settingdefinitionid", null);
			}
			set
			{
				this.SetRelatedEntities<yopower_papps_grid_extensions.earlybound.AppSetting>("settingdefinition_appsetting_settingdefinitionid", null, value);
			}
		}
		
		/// <summary>
		/// 1:N settingdefinition_organizationsetting_settingdefinitionid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("settingdefinition_organizationsetting_settingdefinitionid")]
		public System.Collections.Generic.IEnumerable<yopower_papps_grid_extensions.earlybound.OrganizationSetting> settingdefinition_organizationsetting_settingdefinitionid
		{
			get
			{
				return this.GetRelatedEntities<yopower_papps_grid_extensions.earlybound.OrganizationSetting>("settingdefinition_organizationsetting_settingdefinitionid", null);
			}
			set
			{
				this.SetRelatedEntities<yopower_papps_grid_extensions.earlybound.OrganizationSetting>("settingdefinition_organizationsetting_settingdefinitionid", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_settingdefinition_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_settingdefinition_createdby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_settingdefinition_createdby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_settingdefinition_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_settingdefinition_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_settingdefinition_createdonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_settingdefinition_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_settingdefinition_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_settingdefinition_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_settingdefinition_modifiedby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_settingdefinition_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_settingdefinition_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_settingdefinition_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_settingdefinition_modifiedonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_settingdefinition_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_settingdefinition_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 organization_settingdefinition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_settingdefinition")]
		public yopower_papps_grid_extensions.earlybound.Organization organization_settingdefinition
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.Organization>("organization_settingdefinition", null);
			}
		}
	}
}
#pragma warning restore CS1591
