#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// Determines the status of auto install of Dynamics 365 to Teams attempt has been completed
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_d365autoinstallattemptstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notattempted = 0,
		
		/// <summary>
		/// Dynamics 365 App installed successfully
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Autoinstalled = 1,
		
		/// <summary>
		/// Dynamics 365 app is already installed in Teams
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Alreadyinstalled = 2,
		
		/// <summary>
		/// Teams admin blocked installing Dynamics 365 app
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamsadminblocked = 3,
		
		/// <summary>
		/// Not authorized to execute auto install
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unauthorized = 4,
		
		/// <summary>
		/// D365 auto install solution is no available
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoSolution = 5,
		
		/// <summary>
		/// Graph API is not available for auto install
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoGraphAPI = 6,
		
		/// <summary>
		/// Resource to call graph api is disabled by tenant
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourceDisabled = 7,
	}
	
	/// <summary>
	/// Information that specifies the level of data validation in excel worksheets exported in a format suitable for import.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_datavalidationmodeforexporttoexcel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Full = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
	}
	
	/// <summary>
	/// Default search experience for the user.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_defaultsearchexperience
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Uselastsearch = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relevancesearch = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Categorizedsearch = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customsearch = 3,
	}
	
	/// <summary>
	/// Information that specifies the preferred form mode.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_entityformmode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organizationdefault = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Readoptimized = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Edit = 2,
	}
	
	/// <summary>
	/// Incoming email filtering method.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_incomingemailfilteringmethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allemailmessages = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailmessagesinresponsetoDynamics365email = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailmessagesfromDynamics365LeadsContactsandAccounts = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailmessagesfromDynamics365recordsthatareemailenabled = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noemailmessages = 4,
	}
	
	/// <summary>
	/// Model app channel override
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_releasechannel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Semiannualchanneloverride = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monthlychanneloverride = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Innerchanneloverride = 3,
	}
	
	/// <summary>
	/// Picklist for selecting the user preference for reporting scripting errors.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_reportscripterrors
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AskmeforpermissiontosendanerrorreporttoMicrosoft = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutomaticallysendanerrorreporttoMicrosoftwithoutaskingmeforpermission = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NeversendanerrorreporttoMicrosoftaboutMicrosoftDynamics365 = 3,
	}
	
	/// <summary>
	/// The layout of the visualization pane.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_visualizationpanelayout
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Topbottom = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sidebyside = 1,
	}
	
	/// <summary>
	/// User's preferred settings.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("usersettings")]
	public partial class UserSettings : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the usersettings entity
		/// </summary>
		public partial class Fields
		{
			public const string AddressBookSyncInterval = "addressbooksyncinterval";
			public const string AdvancedFindStartupMode = "advancedfindstartupmode";
			public const string AllowEmailCredentials = "allowemailcredentials";
			public const string AMDesignator = "amdesignator";
			public const string AutoCaptureUserStatus = "autocaptureuserstatus";
			public const string AutoCreateContactOnPromote = "autocreatecontactonpromote";
			public const string BusinessUnitId = "businessunitid";
			public const string CalendarType = "calendartype";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CurrencyDecimalPrecision = "currencydecimalprecision";
			public const string CurrencyFormatCode = "currencyformatcode";
			public const string CurrencySymbol = "currencysymbol";
			public const string D365AutoInstallAttemptStatus = "d365autoinstallattemptstatus";
			public const string DataValidationModeForExportToExcel = "datavalidationmodeforexporttoexcel";
			public const string DateFormatCode = "dateformatcode";
			public const string DateFormatString = "dateformatstring";
			public const string DateSeparator = "dateseparator";
			public const string DecimalSymbol = "decimalsymbol";
			public const string DefaultCalendarView = "defaultcalendarview";
			public const string DefaultCountryCode = "defaultcountrycode";
			public const string DefaultDashboardId = "defaultdashboardid";
			public const string DefaultSearchExperience = "defaultsearchexperience";
			public const string EmailPassword = "emailpassword";
			public const string EmailUsername = "emailusername";
			public const string EntityFormMode = "entityformmode";
			public const string FullNameConventionCode = "fullnameconventioncode";
			public const string GetStartedPaneContentEnabled = "getstartedpanecontentenabled";
			public const string HelpLanguageId = "helplanguageid";
			public const string HomepageArea = "homepagearea";
			public const string HomepageLayout = "homepagelayout";
			public const string HomepageSubarea = "homepagesubarea";
			public const string IgnoreUnsolicitedEmail = "ignoreunsolicitedemail";
			public const string IncomingEmailFilteringMethod = "incomingemailfilteringmethod";
			public const string IsAppsForCrmAlertDismissed = "isappsforcrmalertdismissed";
			public const string IsAutoDataCaptureEnabled = "isautodatacaptureenabled";
			public const string IsDefaultCountryCodeCheckEnabled = "isdefaultcountrycodecheckenabled";
			public const string IsDuplicateDetectionEnabledWhenGoingOnline = "isduplicatedetectionenabledwhengoingonline";
			public const string IsEmailConversationViewEnabled = "isemailconversationviewenabled";
			public const string IsGuidedHelpEnabled = "isguidedhelpenabled";
			public const string IsResourceBookingExchangeSyncEnabled = "isresourcebookingexchangesyncenabled";
			public const string IsSendAsAllowed = "issendasallowed";
			public const string LastAlertsViewedTime = "lastalertsviewedtime";
			public const string LastModifiedTimeForViewPersonalizationSettings = "lastmodifiedtimeforviewpersonalizationsettings";
			public const string LocaleId = "localeid";
			public const string LongDateFormatCode = "longdateformatcode";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string NegativeCurrencyFormatCode = "negativecurrencyformatcode";
			public const string NegativeFormatCode = "negativeformatcode";
			public const string NextTrackingNumber = "nexttrackingnumber";
			public const string NumberGroupFormat = "numbergroupformat";
			public const string NumberSeparator = "numberseparator";
			public const string OfflineSyncInterval = "offlinesyncinterval";
			public const string OutlookSyncInterval = "outlooksyncinterval";
			public const string PagingLimit = "paginglimit";
			public const string PersonalizationSettings = "personalizationsettings";
			public const string PMDesignator = "pmdesignator";
			public const string PreferredSolution = "preferredsolution";
			public const string PricingDecimalPrecision = "pricingdecimalprecision";
			public const string ReleaseChannel = "releasechannel";
			public const string ReportScriptErrors = "reportscripterrors";
			public const string ResourceBookingExchangeSyncVersion = "resourcebookingexchangesyncversion";
			public const string SelectedGlobalFilterId = "selectedglobalfilterid";
			public const string ShowWeekNumber = "showweeknumber";
			public const string SplitViewState = "splitviewstate";
			public const string SyncContactCompany = "synccontactcompany";
			public const string SystemUserId = "systemuserid";
			public const string Id = "systemuserid";
			public const string TableScopedDVSearchFeatureTeachingBubbleViews = "tablescopeddvsearchfeatureteachingbubbleviews";
			public const string TableScopedDVSearchQuickFindTeachingBubbleViews = "tablescopeddvsearchquickfindteachingbubbleviews";
			public const string TimeFormatCode = "timeformatcode";
			public const string TimeFormatString = "timeformatstring";
			public const string TimeSeparator = "timeseparator";
			public const string TimeZoneBias = "timezonebias";
			public const string TimeZoneCode = "timezonecode";
			public const string TimeZoneDaylightBias = "timezonedaylightbias";
			public const string TimeZoneDaylightDay = "timezonedaylightday";
			public const string TimeZoneDaylightDayOfWeek = "timezonedaylightdayofweek";
			public const string TimeZoneDaylightHour = "timezonedaylighthour";
			public const string TimeZoneDaylightMinute = "timezonedaylightminute";
			public const string TimeZoneDaylightMonth = "timezonedaylightmonth";
			public const string TimeZoneDaylightSecond = "timezonedaylightsecond";
			public const string TimeZoneDaylightYear = "timezonedaylightyear";
			public const string TimeZoneStandardBias = "timezonestandardbias";
			public const string TimeZoneStandardDay = "timezonestandardday";
			public const string TimeZoneStandardDayOfWeek = "timezonestandarddayofweek";
			public const string TimeZoneStandardHour = "timezonestandardhour";
			public const string TimeZoneStandardMinute = "timezonestandardminute";
			public const string TimeZoneStandardMonth = "timezonestandardmonth";
			public const string TimeZoneStandardSecond = "timezonestandardsecond";
			public const string TimeZoneStandardYear = "timezonestandardyear";
			public const string TrackingTokenId = "trackingtokenid";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TryToggleSets = "trytogglesets";
			public const string TryToggleStatus = "trytogglestatus";
			public const string UILanguageId = "uilanguageid";
			public const string UseCrmFormForAppointment = "usecrmformforappointment";
			public const string UseCrmFormForContact = "usecrmformforcontact";
			public const string UseCrmFormForEmail = "usecrmformforemail";
			public const string UseCrmFormForTask = "usecrmformfortask";
			public const string UseImageStrips = "useimagestrips";
			public const string UserProfile = "userprofile";
			public const string VersionNumber = "versionnumber";
			public const string VisualizationPaneLayout = "visualizationpanelayout";
			public const string WorkdayStartTime = "workdaystarttime";
			public const string WorkdayStopTime = "workdaystoptime";
			public const string business_unit_user_settings = "business_unit_user_settings";
			public const string lk_usersettings_createdonbehalfby = "lk_usersettings_createdonbehalfby";
			public const string lk_usersettings_modifiedonbehalfby = "lk_usersettings_modifiedonbehalfby";
			public const string lk_usersettingsbase_createdby = "lk_usersettingsbase_createdby";
			public const string lk_usersettingsbase_modifiedby = "lk_usersettingsbase_modifiedby";
			public const string user_settings = "user_settings";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public UserSettings() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "usersettings";
		
		public const string EntityLogicalCollectionName = "usersettingses";
		
		public const string EntitySetName = "usersettingscollection";
		
		/// <summary>
		/// Normal polling frequency used for address book synchronization in Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("addressbooksyncinterval")]
		public System.Nullable<int> AddressBookSyncInterval
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("addressbooksyncinterval");
			}
			set
			{
				this.SetAttributeValue("addressbooksyncinterval", value);
			}
		}
		
		/// <summary>
		/// Default mode, such as simple or detailed, for advanced find.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("advancedfindstartupmode")]
		public System.Nullable<int> AdvancedFindStartupMode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("advancedfindstartupmode");
			}
			set
			{
				this.SetAttributeValue("advancedfindstartupmode", value);
			}
		}
		
		/// <summary>
		/// This attribute is no longer used. The data is now in the Mailbox.AllowEmailConnectorToUseCredentials attribute.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allowemailcredentials")]
		[System.ObsoleteAttribute()]
		public System.Nullable<bool> AllowEmailCredentials
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("allowemailcredentials");
			}
		}
		
		/// <summary>
		/// AM designator to use in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amdesignator")]
		public string AMDesignator
		{
			get
			{
				return this.GetAttributeValue<string>("amdesignator");
			}
			set
			{
				this.SetAttributeValue("amdesignator", value);
			}
		}
		
		/// <summary>
		/// Set user status for ADC Suggestions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocaptureuserstatus")]
		public System.Nullable<int> AutoCaptureUserStatus
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("autocaptureuserstatus");
			}
			set
			{
				this.SetAttributeValue("autocaptureuserstatus", value);
			}
		}
		
		/// <summary>
		/// Auto-create contact on client promote
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocreatecontactonpromote")]
		public System.Nullable<int> AutoCreateContactOnPromote
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("autocreatecontactonpromote");
			}
			set
			{
				this.SetAttributeValue("autocreatecontactonpromote", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit with which the user is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		public System.Nullable<System.Guid> BusinessUnitId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("businessunitid");
			}
			set
			{
				this.SetAttributeValue("businessunitid", value);
			}
		}
		
		/// <summary>
		/// Calendar type for the system. Set to Gregorian US by default.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("calendartype")]
		public System.Nullable<int> CalendarType
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("calendartype");
			}
			set
			{
				this.SetAttributeValue("calendartype", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the user settings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the user settings object was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the usersettings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Number of decimal places that can be used for currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencydecimalprecision")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> CurrencyDecimalPrecision
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("currencydecimalprecision");
			}
			set
			{
				this.SetAttributeValue("currencydecimalprecision", value);
			}
		}
		
		/// <summary>
		/// Information about how currency symbols are placed in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencyformatcode")]
		public System.Nullable<int> CurrencyFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("currencyformatcode");
			}
			set
			{
				this.SetAttributeValue("currencyformatcode", value);
			}
		}
		
		/// <summary>
		/// Symbol used for currency in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencysymbol")]
		public string CurrencySymbol
		{
			get
			{
				return this.GetAttributeValue<string>("currencysymbol");
			}
			set
			{
				this.SetAttributeValue("currencysymbol", value);
			}
		}
		
		/// <summary>
		/// Determines the status of auto install of Dynamics 365 to Teams attempt has been completed
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("d365autoinstallattemptstatus")]
		public virtual usersettings_d365autoinstallattemptstatus? D365AutoInstallAttemptStatus
		{
			get
			{
				return ((usersettings_d365autoinstallattemptstatus?)(EntityOptionSetEnum.GetEnum(this, "d365autoinstallattemptstatus")));
			}
			set
			{
				this.SetAttributeValue("d365autoinstallattemptstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Information that specifies the level of data validation in excel worksheets exported in a format suitable for import.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datavalidationmodeforexporttoexcel")]
		public virtual usersettings_datavalidationmodeforexporttoexcel? DataValidationModeForExportToExcel
		{
			get
			{
				return ((usersettings_datavalidationmodeforexporttoexcel?)(EntityOptionSetEnum.GetEnum(this, "datavalidationmodeforexporttoexcel")));
			}
			set
			{
				this.SetAttributeValue("datavalidationmodeforexporttoexcel", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Information about how the date is displayed in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateformatcode")]
		public System.Nullable<int> DateFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dateformatcode");
			}
			set
			{
				this.SetAttributeValue("dateformatcode", value);
			}
		}
		
		/// <summary>
		/// String showing how the date is displayed throughout Microsoft 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateformatstring")]
		public string DateFormatString
		{
			get
			{
				return this.GetAttributeValue<string>("dateformatstring");
			}
			set
			{
				this.SetAttributeValue("dateformatstring", value);
			}
		}
		
		/// <summary>
		/// Character used to separate the month, the day, and the year in dates in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateseparator")]
		public string DateSeparator
		{
			get
			{
				return this.GetAttributeValue<string>("dateseparator");
			}
			set
			{
				this.SetAttributeValue("dateseparator", value);
			}
		}
		
		/// <summary>
		/// Symbol used for decimal in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("decimalsymbol")]
		public string DecimalSymbol
		{
			get
			{
				return this.GetAttributeValue<string>("decimalsymbol");
			}
			set
			{
				this.SetAttributeValue("decimalsymbol", value);
			}
		}
		
		/// <summary>
		/// Default calendar view for the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultcalendarview")]
		public System.Nullable<int> DefaultCalendarView
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defaultcalendarview");
			}
			set
			{
				this.SetAttributeValue("defaultcalendarview", value);
			}
		}
		
		/// <summary>
		/// Text area to enter default country code.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultcountrycode")]
		public string DefaultCountryCode
		{
			get
			{
				return this.GetAttributeValue<string>("defaultcountrycode");
			}
			set
			{
				this.SetAttributeValue("defaultcountrycode", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the default dashboard.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultdashboardid")]
		public System.Nullable<System.Guid> DefaultDashboardId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defaultdashboardid");
			}
			set
			{
				this.SetAttributeValue("defaultdashboardid", value);
			}
		}
		
		/// <summary>
		/// Default search experience for the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultsearchexperience")]
		public virtual usersettings_defaultsearchexperience? DefaultSearchExperience
		{
			get
			{
				return ((usersettings_defaultsearchexperience?)(EntityOptionSetEnum.GetEnum(this, "defaultsearchexperience")));
			}
			set
			{
				this.SetAttributeValue("defaultsearchexperience", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// This attribute is no longer used. The data is now in the Mailbox.Password attribute.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailpassword")]
		[System.ObsoleteAttribute()]
		public string EmailPassword
		{
			get
			{
				return this.GetAttributeValue<string>("emailpassword");
			}
		}
		
		/// <summary>
		/// This attribute is no longer used. The data is now in the Mailbox.UserName attribute.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailusername")]
		[System.ObsoleteAttribute()]
		public string EmailUsername
		{
			get
			{
				return this.GetAttributeValue<string>("emailusername");
			}
		}
		
		/// <summary>
		/// Indicates the form mode to be used.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityformmode")]
		public virtual usersettings_entityformmode? EntityFormMode
		{
			get
			{
				return ((usersettings_entityformmode?)(EntityOptionSetEnum.GetEnum(this, "entityformmode")));
			}
			set
			{
				this.SetAttributeValue("entityformmode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Order in which names are to be displayed in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fullnameconventioncode")]
		public System.Nullable<int> FullNameConventionCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("fullnameconventioncode");
			}
			set
			{
				this.SetAttributeValue("fullnameconventioncode", value);
			}
		}
		
		/// <summary>
		/// Information that specifies whether the Get Started pane in lists is enabled.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("getstartedpanecontentenabled")]
		public System.Nullable<bool> GetStartedPaneContentEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("getstartedpanecontentenabled");
			}
			set
			{
				this.SetAttributeValue("getstartedpanecontentenabled", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the Help language.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("helplanguageid")]
		public System.Nullable<int> HelpLanguageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("helplanguageid");
			}
			set
			{
				this.SetAttributeValue("helplanguageid", value);
			}
		}
		
		/// <summary>
		/// Web site home page for the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagearea")]
		public string HomepageArea
		{
			get
			{
				return this.GetAttributeValue<string>("homepagearea");
			}
			set
			{
				this.SetAttributeValue("homepagearea", value);
			}
		}
		
		/// <summary>
		/// Configuration of the home page layout.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagelayout")]
		public string HomepageLayout
		{
			get
			{
				return this.GetAttributeValue<string>("homepagelayout");
			}
			set
			{
				this.SetAttributeValue("homepagelayout", value);
			}
		}
		
		/// <summary>
		/// Web site page for the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagesubarea")]
		public string HomepageSubarea
		{
			get
			{
				return this.GetAttributeValue<string>("homepagesubarea");
			}
			set
			{
				this.SetAttributeValue("homepagesubarea", value);
			}
		}
		
		/// <summary>
		/// Information that specifies whether a user account is to ignore unsolicited email (deprecated).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ignoreunsolicitedemail")]
		public System.Nullable<bool> IgnoreUnsolicitedEmail
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ignoreunsolicitedemail");
			}
			set
			{
				this.SetAttributeValue("ignoreunsolicitedemail", value);
			}
		}
		
		/// <summary>
		/// Incoming email filtering method.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incomingemailfilteringmethod")]
		public virtual usersettings_incomingemailfilteringmethod? IncomingEmailFilteringMethod
		{
			get
			{
				return ((usersettings_incomingemailfilteringmethod?)(EntityOptionSetEnum.GetEnum(this, "incomingemailfilteringmethod")));
			}
			set
			{
				this.SetAttributeValue("incomingemailfilteringmethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Show or dismiss alert for Apps for 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isappsforcrmalertdismissed")]
		public System.Nullable<bool> IsAppsForCrmAlertDismissed
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isappsforcrmalertdismissed");
			}
			set
			{
				this.SetAttributeValue("isappsforcrmalertdismissed", value);
			}
		}
		
		/// <summary>
		/// Indicates whether to use the Auto Capture feature enabled or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isautodatacaptureenabled")]
		public System.Nullable<bool> IsAutoDataCaptureEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isautodatacaptureenabled");
			}
			set
			{
				this.SetAttributeValue("isautodatacaptureenabled", value);
			}
		}
		
		/// <summary>
		/// Enable or disable country code selection .
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefaultcountrycodecheckenabled")]
		public System.Nullable<bool> IsDefaultCountryCodeCheckEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdefaultcountrycodecheckenabled");
			}
			set
			{
				this.SetAttributeValue("isdefaultcountrycodecheckenabled", value);
			}
		}
		
		/// <summary>
		/// Indicates if duplicate detection is enabled when going online.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isduplicatedetectionenabledwhengoingonline")]
		public System.Nullable<bool> IsDuplicateDetectionEnabledWhenGoingOnline
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isduplicatedetectionenabledwhengoingonline");
			}
			set
			{
				this.SetAttributeValue("isduplicatedetectionenabledwhengoingonline", value);
			}
		}
		
		/// <summary>
		/// Enable or disable email conversation view on timeline wall selection.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isemailconversationviewenabled")]
		public System.Nullable<bool> IsEmailConversationViewEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isemailconversationviewenabled");
			}
			set
			{
				this.SetAttributeValue("isemailconversationviewenabled", value);
			}
		}
		
		/// <summary>
		/// Enable or disable guided help.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isguidedhelpenabled")]
		public System.Nullable<bool> IsGuidedHelpEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isguidedhelpenabled");
			}
			set
			{
				this.SetAttributeValue("isguidedhelpenabled", value);
			}
		}
		
		/// <summary>
		/// Indicates if the synchronization of user resource booking with Exchange is enabled at user level.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isresourcebookingexchangesyncenabled")]
		public System.Nullable<bool> IsResourceBookingExchangeSyncEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isresourcebookingexchangesyncenabled");
			}
			set
			{
				this.SetAttributeValue("isresourcebookingexchangesyncenabled", value);
			}
		}
		
		/// <summary>
		/// Indicates if send as other user privilege is enabled or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("issendasallowed")]
		public System.Nullable<bool> IsSendAsAllowed
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("issendasallowed");
			}
			set
			{
				this.SetAttributeValue("issendasallowed", value);
			}
		}
		
		/// <summary>
		/// Shows the last time when the traces were read from the database.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastalertsviewedtime")]
		public System.Nullable<System.DateTime> LastAlertsViewedTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastalertsviewedtime");
			}
			set
			{
				this.SetAttributeValue("lastalertsviewedtime", value);
			}
		}
		
		/// <summary>
		/// Stores the timestamp for when the ViewPersonalizationSettings attribute was updated for this user in the UserEntityUISettings table.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastmodifiedtimeforviewpersonalizationsettings")]
		public System.Nullable<System.DateTime> LastModifiedTimeForViewPersonalizationSettings
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastmodifiedtimeforviewpersonalizationsettings");
			}
			set
			{
				this.SetAttributeValue("lastmodifiedtimeforviewpersonalizationsettings", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user locale.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("localeid")]
		public System.Nullable<int> LocaleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("localeid");
			}
			set
			{
				this.SetAttributeValue("localeid", value);
			}
		}
		
		/// <summary>
		/// Information that specifies how Long Date is displayed throughout Microsoft 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("longdateformatcode")]
		public System.Nullable<int> LongDateFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("longdateformatcode");
			}
			set
			{
				this.SetAttributeValue("longdateformatcode", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who last modified the user settings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the user settings object was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the usersettings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Information that specifies how negative currency numbers are displayed in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("negativecurrencyformatcode")]
		public System.Nullable<int> NegativeCurrencyFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("negativecurrencyformatcode");
			}
			set
			{
				this.SetAttributeValue("negativecurrencyformatcode", value);
			}
		}
		
		/// <summary>
		/// Information that specifies how negative numbers are displayed in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("negativeformatcode")]
		public System.Nullable<int> NegativeFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("negativeformatcode");
			}
			set
			{
				this.SetAttributeValue("negativeformatcode", value);
			}
		}
		
		/// <summary>
		/// Next tracking number.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nexttrackingnumber")]
		public System.Nullable<int> NextTrackingNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("nexttrackingnumber");
			}
			set
			{
				this.SetAttributeValue("nexttrackingnumber", value);
			}
		}
		
		/// <summary>
		/// Information that specifies how numbers are grouped in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numbergroupformat")]
		public string NumberGroupFormat
		{
			get
			{
				return this.GetAttributeValue<string>("numbergroupformat");
			}
			set
			{
				this.SetAttributeValue("numbergroupformat", value);
			}
		}
		
		/// <summary>
		/// Symbol used for number separation in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numberseparator")]
		public string NumberSeparator
		{
			get
			{
				return this.GetAttributeValue<string>("numberseparator");
			}
			set
			{
				this.SetAttributeValue("numberseparator", value);
			}
		}
		
		/// <summary>
		/// Normal polling frequency used for background offline synchronization in Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("offlinesyncinterval")]
		public System.Nullable<int> OfflineSyncInterval
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("offlinesyncinterval");
			}
			set
			{
				this.SetAttributeValue("offlinesyncinterval", value);
			}
		}
		
		/// <summary>
		/// Normal polling frequency used for record synchronization in Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("outlooksyncinterval")]
		public System.Nullable<int> OutlookSyncInterval
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("outlooksyncinterval");
			}
			set
			{
				this.SetAttributeValue("outlooksyncinterval", value);
			}
		}
		
		/// <summary>
		/// Information that specifies how many items to list on a page in list views.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paginglimit")]
		public System.Nullable<int> PagingLimit
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("paginglimit");
			}
			set
			{
				this.SetAttributeValue("paginglimit", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("personalizationsettings")]
		public string PersonalizationSettings
		{
			get
			{
				return this.GetAttributeValue<string>("personalizationsettings");
			}
			set
			{
				this.SetAttributeValue("personalizationsettings", value);
			}
		}
		
		/// <summary>
		/// PM designator to use in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pmdesignator")]
		public string PMDesignator
		{
			get
			{
				return this.GetAttributeValue<string>("pmdesignator");
			}
			set
			{
				this.SetAttributeValue("pmdesignator", value);
			}
		}
		
		/// <summary>
		/// Preferred Solution when create a component without under a solution in this organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("preferredsolution")]
		public Microsoft.Xrm.Sdk.EntityReference PreferredSolution
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("preferredsolution");
			}
			set
			{
				this.SetAttributeValue("preferredsolution", value);
			}
		}
		
		/// <summary>
		/// Number of decimal places that can be used for prices.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingdecimalprecision")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> PricingDecimalPrecision
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pricingdecimalprecision");
			}
			set
			{
				this.SetAttributeValue("pricingdecimalprecision", value);
			}
		}
		
		/// <summary>
		/// Model app channel override
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("releasechannel")]
		public virtual usersettings_releasechannel? ReleaseChannel
		{
			get
			{
				return ((usersettings_releasechannel?)(EntityOptionSetEnum.GetEnum(this, "releasechannel")));
			}
			set
			{
				this.SetAttributeValue("releasechannel", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Picklist for selecting the user preference for reporting scripting errors.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("reportscripterrors")]
		public virtual usersettings_reportscripterrors? ReportScriptErrors
		{
			get
			{
				return ((usersettings_reportscripterrors?)(EntityOptionSetEnum.GetEnum(this, "reportscripterrors")));
			}
			set
			{
				this.SetAttributeValue("reportscripterrors", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// The version number for resource booking synchronization with Exchange.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resourcebookingexchangesyncversion")]
		public System.Nullable<long> ResourceBookingExchangeSyncVersion
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("resourcebookingexchangesyncversion");
			}
			set
			{
				this.SetAttributeValue("resourcebookingexchangesyncversion", value);
			}
		}
		
		/// <summary>
		/// Store selected customer service hub dashboard saved filter id.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("selectedglobalfilterid")]
		public System.Nullable<System.Guid> SelectedGlobalFilterId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("selectedglobalfilterid");
			}
			set
			{
				this.SetAttributeValue("selectedglobalfilterid", value);
			}
		}
		
		/// <summary>
		/// Information that specifies whether to display the week number in calendar displays in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("showweeknumber")]
		public System.Nullable<bool> ShowWeekNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("showweeknumber");
			}
			set
			{
				this.SetAttributeValue("showweeknumber", value);
			}
		}
		
		/// <summary>
		/// For Internal use only
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("splitviewstate")]
		public System.Nullable<bool> SplitViewState
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("splitviewstate");
			}
			set
			{
				this.SetAttributeValue("splitviewstate", value);
			}
		}
		
		/// <summary>
		/// Indicates if the company field in Microsoft Office Outlook items are set during Outlook synchronization.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("synccontactcompany")]
		public System.Nullable<bool> SyncContactCompany
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("synccontactcompany");
			}
			set
			{
				this.SetAttributeValue("synccontactcompany", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		public System.Nullable<System.Guid> SystemUserId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("systemuserid");
			}
			set
			{
				this.SetAttributeValue("systemuserid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SystemUserId = value;
			}
		}
		
		/// <summary>
		/// The number of times a user has interacted with the Tabled Scoped Dataverse Search feature teaching bubble.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("tablescopeddvsearchfeatureteachingbubbleviews")]
		public System.Nullable<int> TableScopedDVSearchFeatureTeachingBubbleViews
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("tablescopeddvsearchfeatureteachingbubbleviews");
			}
			set
			{
				this.SetAttributeValue("tablescopeddvsearchfeatureteachingbubbleviews", value);
			}
		}
		
		/// <summary>
		/// The number of times a user has interacted with the Tabled Scoped Dataverse Search Quick Find teaching bubble.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("tablescopeddvsearchquickfindteachingbubbleviews")]
		public System.Nullable<int> TableScopedDVSearchQuickFindTeachingBubbleViews
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("tablescopeddvsearchquickfindteachingbubbleviews");
			}
			set
			{
				this.SetAttributeValue("tablescopeddvsearchquickfindteachingbubbleviews", value);
			}
		}
		
		/// <summary>
		/// Information that specifies how the time is displayed in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeformatcode")]
		public System.Nullable<int> TimeFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timeformatcode");
			}
			set
			{
				this.SetAttributeValue("timeformatcode", value);
			}
		}
		
		/// <summary>
		/// Text for how time is displayed in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeformatstring")]
		public string TimeFormatString
		{
			get
			{
				return this.GetAttributeValue<string>("timeformatstring");
			}
			set
			{
				this.SetAttributeValue("timeformatstring", value);
			}
		}
		
		/// <summary>
		/// Text for how time is displayed in Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeseparator")]
		public string TimeSeparator
		{
			get
			{
				return this.GetAttributeValue<string>("timeseparator");
			}
			set
			{
				this.SetAttributeValue("timeseparator", value);
			}
		}
		
		/// <summary>
		/// Local time zone adjustment for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonebias")]
		public System.Nullable<int> TimeZoneBias
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonebias");
			}
			set
			{
				this.SetAttributeValue("timezonebias", value);
			}
		}
		
		/// <summary>
		/// Local time zone for the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonecode")]
		public System.Nullable<int> TimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonecode");
			}
			set
			{
				this.SetAttributeValue("timezonecode", value);
			}
		}
		
		/// <summary>
		/// Local time zone daylight adjustment for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightbias")]
		public System.Nullable<int> TimeZoneDaylightBias
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightbias");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightbias", value);
			}
		}
		
		/// <summary>
		/// Local time zone daylight day for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightday")]
		public System.Nullable<int> TimeZoneDaylightDay
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightday");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightday", value);
			}
		}
		
		/// <summary>
		/// Local time zone daylight day of week for the user. System calculated based on the time zone selected in Options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightdayofweek")]
		public System.Nullable<int> TimeZoneDaylightDayOfWeek
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightdayofweek");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightdayofweek", value);
			}
		}
		
		/// <summary>
		/// Local time zone daylight hour for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylighthour")]
		public System.Nullable<int> TimeZoneDaylightHour
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylighthour");
			}
			set
			{
				this.SetAttributeValue("timezonedaylighthour", value);
			}
		}
		
		/// <summary>
		/// Local time zone daylight minute for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightminute")]
		public System.Nullable<int> TimeZoneDaylightMinute
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightminute");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightminute", value);
			}
		}
		
		/// <summary>
		/// Local time zone daylight month for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightmonth")]
		public System.Nullable<int> TimeZoneDaylightMonth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightmonth");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightmonth", value);
			}
		}
		
		/// <summary>
		/// Local time zone daylight second for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightsecond")]
		public System.Nullable<int> TimeZoneDaylightSecond
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightsecond");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightsecond", value);
			}
		}
		
		/// <summary>
		/// Local time zone daylight year for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightyear")]
		public System.Nullable<int> TimeZoneDaylightYear
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightyear");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightyear", value);
			}
		}
		
		/// <summary>
		/// Local time zone standard time bias for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardbias")]
		public System.Nullable<int> TimeZoneStandardBias
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardbias");
			}
			set
			{
				this.SetAttributeValue("timezonestandardbias", value);
			}
		}
		
		/// <summary>
		/// Local time zone standard day for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardday")]
		public System.Nullable<int> TimeZoneStandardDay
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardday");
			}
			set
			{
				this.SetAttributeValue("timezonestandardday", value);
			}
		}
		
		/// <summary>
		/// Local time zone standard day of week for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandarddayofweek")]
		public System.Nullable<int> TimeZoneStandardDayOfWeek
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandarddayofweek");
			}
			set
			{
				this.SetAttributeValue("timezonestandarddayofweek", value);
			}
		}
		
		/// <summary>
		/// Local time zone standard hour for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardhour")]
		public System.Nullable<int> TimeZoneStandardHour
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardhour");
			}
			set
			{
				this.SetAttributeValue("timezonestandardhour", value);
			}
		}
		
		/// <summary>
		/// Local time zone standard minute for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardminute")]
		public System.Nullable<int> TimeZoneStandardMinute
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardminute");
			}
			set
			{
				this.SetAttributeValue("timezonestandardminute", value);
			}
		}
		
		/// <summary>
		/// Local time zone standard month for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardmonth")]
		public System.Nullable<int> TimeZoneStandardMonth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardmonth");
			}
			set
			{
				this.SetAttributeValue("timezonestandardmonth", value);
			}
		}
		
		/// <summary>
		/// Local time zone standard second for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardsecond")]
		public System.Nullable<int> TimeZoneStandardSecond
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardsecond");
			}
			set
			{
				this.SetAttributeValue("timezonestandardsecond", value);
			}
		}
		
		/// <summary>
		/// Local time zone standard year for the user. System calculated based on the time zone selected.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardyear")]
		public System.Nullable<int> TimeZoneStandardYear
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardyear");
			}
			set
			{
				this.SetAttributeValue("timezonestandardyear", value);
			}
		}
		
		/// <summary>
		/// Tracking token ID.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trackingtokenid")]
		public System.Nullable<int> TrackingTokenId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("trackingtokenid");
			}
			set
			{
				this.SetAttributeValue("trackingtokenid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the default currency of the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		/// <summary>
		/// The list of app modules with try toggle sets
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trytogglesets")]
		public string TryToggleSets
		{
			get
			{
				return this.GetAttributeValue<string>("trytogglesets");
			}
			set
			{
				this.SetAttributeValue("trytogglesets", value);
			}
		}
		
		/// <summary>
		/// Enable or disable try toggle status.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trytogglestatus")]
		public System.Nullable<bool> TryToggleStatus
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("trytogglestatus");
			}
			set
			{
				this.SetAttributeValue("trytogglestatus", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the language in which to view the user interface (UI).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uilanguageid")]
		public System.Nullable<int> UILanguageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("uilanguageid");
			}
			set
			{
				this.SetAttributeValue("uilanguageid", value);
			}
		}
		
		/// <summary>
		/// Indicates whether to use the Microsoft Dynamics 365 appointment form within Microsoft Office Outlook for creating new appointments.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforappointment")]
		public System.Nullable<bool> UseCrmFormForAppointment
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforappointment");
			}
			set
			{
				this.SetAttributeValue("usecrmformforappointment", value);
			}
		}
		
		/// <summary>
		/// Indicates whether to use the Microsoft Dynamics 365 contact form within Microsoft Office Outlook for creating new contacts.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforcontact")]
		public System.Nullable<bool> UseCrmFormForContact
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforcontact");
			}
			set
			{
				this.SetAttributeValue("usecrmformforcontact", value);
			}
		}
		
		/// <summary>
		/// Indicates whether to use the Microsoft Dynamics 365 email form within Microsoft Office Outlook for creating new emails.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforemail")]
		public System.Nullable<bool> UseCrmFormForEmail
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforemail");
			}
			set
			{
				this.SetAttributeValue("usecrmformforemail", value);
			}
		}
		
		/// <summary>
		/// Indicates whether to use the Microsoft Dynamics 365 task form within Microsoft Office Outlook for creating new tasks.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformfortask")]
		public System.Nullable<bool> UseCrmFormForTask
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformfortask");
			}
			set
			{
				this.SetAttributeValue("usecrmformfortask", value);
			}
		}
		
		/// <summary>
		/// Indicates whether image strips are used to render images.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("useimagestrips")]
		public System.Nullable<bool> UseImageStrips
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("useimagestrips");
			}
			set
			{
				this.SetAttributeValue("useimagestrips", value);
			}
		}
		
		/// <summary>
		/// Specifies user profile ids in comma separated list.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("userprofile")]
		public string UserProfile
		{
			get
			{
				return this.GetAttributeValue<string>("userprofile");
			}
			set
			{
				this.SetAttributeValue("userprofile", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// The layout of the visualization pane.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("visualizationpanelayout")]
		public virtual usersettings_visualizationpanelayout? VisualizationPaneLayout
		{
			get
			{
				return ((usersettings_visualizationpanelayout?)(EntityOptionSetEnum.GetEnum(this, "visualizationpanelayout")));
			}
			set
			{
				this.SetAttributeValue("visualizationpanelayout", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Workday start time for the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workdaystarttime")]
		public string WorkdayStartTime
		{
			get
			{
				return this.GetAttributeValue<string>("workdaystarttime");
			}
			set
			{
				this.SetAttributeValue("workdaystarttime", value);
			}
		}
		
		/// <summary>
		/// Workday stop time for the user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workdaystoptime")]
		public string WorkdayStopTime
		{
			get
			{
				return this.GetAttributeValue<string>("workdaystoptime");
			}
			set
			{
				this.SetAttributeValue("workdaystoptime", value);
			}
		}
		
		/// <summary>
		/// N:1 business_unit_user_settings
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_user_settings")]
		public yopower_papps_grid_extensions.earlybound.BusinessUnit business_unit_user_settings
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.BusinessUnit>("business_unit_user_settings", null);
			}
			set
			{
				this.SetRelatedEntity<yopower_papps_grid_extensions.earlybound.BusinessUnit>("business_unit_user_settings", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettings_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettings_createdonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_usersettings_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_usersettings_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettings_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettings_modifiedonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_usersettings_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_usersettings_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettingsbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettingsbase_createdby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_usersettingsbase_createdby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_usersettingsbase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettingsbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettingsbase_modifiedby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_usersettingsbase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_usersettingsbase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_settings
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_settings")]
		public yopower_papps_grid_extensions.earlybound.SystemUser user_settings
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("user_settings", null);
			}
			set
			{
				this.SetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("user_settings", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
