#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// Status of the Column Definition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum yp_pagridextd_column_definition_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Column Definition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum yp_pagridextd_column_definition_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("yp_pagridextd_column_definition")]
	public partial class yp_pagridextd_column_definition : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the yp_pagridextd_column_definition entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string yp_allow_pin = "yp_allow_pin";
			public const string yp_based_on_optionset_column = "yp_based_on_optionset_column";
			public const string yp_editable = "yp_editable";
			public const string yp_elegible_for_security_roles = "yp_elegible_for_security_roles";
			public const string yp_mode = "yp_mode";
			public const string yp_name = "yp_name";
			public const string yp_optionset_criteria = "yp_optionset_criteria";
			public const string yp_optionset_values = "yp_optionset_values";
			public const string yp_pagridextd_column_definitionId = "yp_pagridextd_column_definitionid";
			public const string Id = "yp_pagridextd_column_definitionid";
			public const string yp_parameters = "yp_parameters";
			public const string yp_rename_column = "yp_rename_column";
			public const string yp_shortcut = "yp_shortcut";
			public const string yp_subgrid_column = "yp_subgrid_column";
			public const string yp_subgrid_name = "yp_subgrid_name";
			public const string yp_subgrid_table = "yp_subgrid_table";
			public const string yp_type = "yp_type";
			public const string lk_yp_pagridextd_column_definition_createdby = "lk_yp_pagridextd_column_definition_createdby";
			public const string lk_yp_pagridextd_column_definition_createdonbehalfby = "lk_yp_pagridextd_column_definition_createdonbehalfby";
			public const string lk_yp_pagridextd_column_definition_modifiedby = "lk_yp_pagridextd_column_definition_modifiedby";
			public const string lk_yp_pagridextd_column_definition_modifiedonbehalfby = "lk_yp_pagridextd_column_definition_modifiedonbehalfby";
			public const string organization_yp_pagridextd_column_definition = "organization_yp_pagridextd_column_definition";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public yp_pagridextd_column_definition() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "yp_pagridextd_column_definition";
		
		public const string EntityLogicalCollectionName = "yp_pagridextd_column_definitions";
		
		public const string EntitySetName = "yp_pagridextd_column_definitions";
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Status of the Column Definition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual yp_pagridextd_column_definition_statecode? statecode
		{
			get
			{
				return ((yp_pagridextd_column_definition_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Column Definition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual yp_pagridextd_column_definition_statuscode? statuscode
		{
			get
			{
				return ((yp_pagridextd_column_definition_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_allow_pin")]
		public System.Nullable<bool> yp_allow_pin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("yp_allow_pin");
			}
			set
			{
				this.SetAttributeValue("yp_allow_pin", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_based_on_optionset_column")]
		public string yp_based_on_optionset_column
		{
			get
			{
				return this.GetAttributeValue<string>("yp_based_on_optionset_column");
			}
			set
			{
				this.SetAttributeValue("yp_based_on_optionset_column", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_editable")]
		public System.Nullable<bool> yp_editable
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("yp_editable");
			}
			set
			{
				this.SetAttributeValue("yp_editable", value);
			}
		}
		
		/// <summary>
		/// Splited by comma
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_elegible_for_security_roles")]
		public string yp_elegible_for_security_roles
		{
			get
			{
				return this.GetAttributeValue<string>("yp_elegible_for_security_roles");
			}
			set
			{
				this.SetAttributeValue("yp_elegible_for_security_roles", value);
			}
		}
		
		/// <summary>
		/// Populated by Plugin
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_mode")]
		public virtual yp_gbl_column_mode? yp_mode
		{
			get
			{
				return ((yp_gbl_column_mode?)(EntityOptionSetEnum.GetEnum(this, "yp_mode")));
			}
			set
			{
				this.SetAttributeValue("yp_mode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_name")]
		public string yp_name
		{
			get
			{
				return this.GetAttributeValue<string>("yp_name");
			}
			set
			{
				this.SetAttributeValue("yp_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_optionset_criteria")]
		public virtual yp_gbl_column_definition_pptionset_criteria? yp_optionset_criteria
		{
			get
			{
				return ((yp_gbl_column_definition_pptionset_criteria?)(EntityOptionSetEnum.GetEnum(this, "yp_optionset_criteria")));
			}
			set
			{
				this.SetAttributeValue("yp_optionset_criteria", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_optionset_values")]
		public string yp_optionset_values
		{
			get
			{
				return this.GetAttributeValue<string>("yp_optionset_values");
			}
			set
			{
				this.SetAttributeValue("yp_optionset_values", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_pagridextd_column_definitionid")]
		public System.Nullable<System.Guid> yp_pagridextd_column_definitionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("yp_pagridextd_column_definitionid");
			}
			set
			{
				this.SetAttributeValue("yp_pagridextd_column_definitionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_pagridextd_column_definitionid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.yp_pagridextd_column_definitionId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_parameters")]
		public string yp_parameters
		{
			get
			{
				return this.GetAttributeValue<string>("yp_parameters");
			}
			set
			{
				this.SetAttributeValue("yp_parameters", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_rename_column")]
		public string yp_rename_column
		{
			get
			{
				return this.GetAttributeValue<string>("yp_rename_column");
			}
			set
			{
				this.SetAttributeValue("yp_rename_column", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_shortcut")]
		public virtual yp_gbl_column_definition_shortcut? yp_shortcut
		{
			get
			{
				return ((yp_gbl_column_definition_shortcut?)(EntityOptionSetEnum.GetEnum(this, "yp_shortcut")));
			}
			set
			{
				this.SetAttributeValue("yp_shortcut", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Table Column Logical Name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_subgrid_column")]
		public string yp_subgrid_column
		{
			get
			{
				return this.GetAttributeValue<string>("yp_subgrid_column");
			}
			set
			{
				this.SetAttributeValue("yp_subgrid_column", value);
			}
		}
		
		/// <summary>
		/// Subgrid Logical Name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_subgrid_name")]
		public string yp_subgrid_name
		{
			get
			{
				return this.GetAttributeValue<string>("yp_subgrid_name");
			}
			set
			{
				this.SetAttributeValue("yp_subgrid_name", value);
			}
		}
		
		/// <summary>
		/// Subgrid Table Logical Name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_subgrid_table")]
		public string yp_subgrid_table
		{
			get
			{
				return this.GetAttributeValue<string>("yp_subgrid_table");
			}
			set
			{
				this.SetAttributeValue("yp_subgrid_table", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yp_type")]
		public virtual yp_gbl_column_definition_type? yp_type
		{
			get
			{
				return ((yp_gbl_column_definition_type?)(EntityOptionSetEnum.GetEnum(this, "yp_type")));
			}
			set
			{
				this.SetAttributeValue("yp_type", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// N:1 lk_yp_pagridextd_column_definition_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_yp_pagridextd_column_definition_createdby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_yp_pagridextd_column_definition_createdby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_yp_pagridextd_column_definition_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_yp_pagridextd_column_definition_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_yp_pagridextd_column_definition_createdonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_yp_pagridextd_column_definition_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_yp_pagridextd_column_definition_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_yp_pagridextd_column_definition_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_yp_pagridextd_column_definition_modifiedby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_yp_pagridextd_column_definition_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_yp_pagridextd_column_definition_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_yp_pagridextd_column_definition_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_yp_pagridextd_column_definition_modifiedonbehalfby")]
		public yopower_papps_grid_extensions.earlybound.SystemUser lk_yp_pagridextd_column_definition_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.SystemUser>("lk_yp_pagridextd_column_definition_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 organization_yp_pagridextd_column_definition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_yp_pagridextd_column_definition")]
		public yopower_papps_grid_extensions.earlybound.Organization organization_yp_pagridextd_column_definition
		{
			get
			{
				return this.GetRelatedEntity<yopower_papps_grid_extensions.earlybound.Organization>("organization_yp_pagridextd_column_definition", null);
			}
		}
	}
}
#pragma warning restore CS1591
