#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace yopower_papps_grid_extensions.earlybound
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.AppModule"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.AppModule> AppModuleSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.AppModule>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.AppSetting"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.AppSetting> AppSettingSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.AppSetting>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.BusinessUnit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.BusinessUnit> BusinessUnitSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.BusinessUnit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.EntityDataProvider"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.EntityDataProvider> EntityDataProviderSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.EntityDataProvider>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.EntityDataSource"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.EntityDataSource> EntityDataSourceSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.EntityDataSource>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.LanguageLocale"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.LanguageLocale> LanguageLocaleSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.LanguageLocale>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.Organization"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.Organization> OrganizationSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.Organization>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.OrganizationSetting"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.OrganizationSetting> OrganizationSettingSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.OrganizationSetting>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.Role"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.Role> RoleSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.Role>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.SavedQuery"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.SavedQuery> SavedQuerySet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.SavedQuery>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.SettingDefinition"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.SettingDefinition> SettingDefinitionSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.SettingDefinition>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.SystemUserRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.SystemUserRoles> SystemUserRolesSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.SystemUserRoles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.Team"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.Team> TeamSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.Team>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.TeamMembership"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.TeamMembership> TeamMembershipSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.TeamMembership>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.TeamRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.TeamRoles> TeamRolesSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.TeamRoles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.UserSettings"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.UserSettings> UserSettingsSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.UserSettings>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.WebResource"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.WebResource> WebResourceSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.WebResource>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="yopower_papps_grid_extensions.earlybound.yp_pagridextd_column_definition"/> entities.
		/// </summary>
		public System.Linq.IQueryable<yopower_papps_grid_extensions.earlybound.yp_pagridextd_column_definition> yp_pagridextd_column_definitionSet
		{
			get
			{
				return this.CreateQuery<yopower_papps_grid_extensions.earlybound.yp_pagridextd_column_definition>();
			}
		}
	}
}
#pragma warning restore CS1591
